- name: integration of terraform and ansible
  hosts: localhost
  become: true

  tasks:
  - name: installing httpd
    apt:
      name: apache2
      state: present
  - name: installing php
    apt:
      name: php
      state: present
  - name: starting httpd service
    service:
      name: apache2
      state: started
  - name: installing git
    apt:
      name: git
      state: present
  - name: formatting storage
    filesystem:
      fstype: ext4
      dev: /dev/xvdh
  - name: making folder
    file:
      path: /var/www/html/web
      state: directory
  - name: mounting storage
    mount:
      fstype: ext4
      src: /dev/xvdh
      path: /var/www/html
      state: mounted
  - name: cloning git repo
    git:
      repo: "https://github.com/jaimefernandezjr/my-portfolio-website.git"
      dest: /var/www/html/web
